// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoDeportiva.Areas.Identity.Data;
using proyectoDeportiva.Data;

#nullable disable

namespace proyectoDeportiva.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity<Pista>( b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR(20)")
                        .HasConversion<string>(); ;
                       

                    b.Property<TimeSpan>("HorarioApertura")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HorarioCierre")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeporte")
                        .HasColumnType("VARCHAR(20)")
                        .HasConversion<string>(); ;


                    b.HasKey("Id");

                    b.ToTable("pista", (string)null);
                });

            modelBuilder.Entity("proyectoDeportiva.Areas.Identity.Data.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DiaReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdPista")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdPista");

                    b.HasIndex("IdUsuario");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("proyectoDeportiva.Areas.Identity.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(256)
						.HasColumnType("varchar(256)");

					b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rol")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");


                    b.Property<string>("DNI")
                        .HasColumnType("char(9)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");


                    b.HasKey("Id");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex");

					b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("proyectoDeportiva.Areas.Identity.Data.Reserva", b =>
                {
                    b.HasOne("proyectoDeportiva.Areas.Identity.Data.Pista", "Pista")
                        .WithMany()
                        .HasForeignKey("IdPista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectoDeportiva.Areas.Identity.Data.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Pista");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
